services:
  python-app:
    build: .
    container_name: python-app
    restart: unless-stopped
    environment:
      - OEDON_PUBLIC_KEY=${OEDON_PUBLIC_KEY}
    networks:
      - oedon-network

networks:
  oedon-network:
    external: true
