version: '3.8'
services:
  my-app:
    image: nginx:alpine
    container_name: my-app  # Este nombre es el que pondrás en apps.list
    networks:
      - oedon-network

networks:
  oedon-network:
    external: true
