services:
  wordpress:
    image: wordpress:php8.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    networks:
      - oedon-network

volumes:
  wordpress_data:
    external: true
    name: oedon_universal_wp_data

networks:
  oedon-network:
    external: true
